parameters:
#    travel_travel.example.class: Travel\TravelBundle\Example

services:
#    travel_travel.example:
#        class: %travel_travel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
